### PR TITLE
a little styling here and there

### PR DESCRIPTION
**Pull request by browniecharl**

### CODE REVIEW

**Comment by browniecharl** [comment]
I was able to get the votes to show on the homepage and dashboard. They arent displaying correctly on the review page, and they arent updating on click

**Review by kgil60 — DISMISSED** [review]
I think you're missing a closing ')' in the sequelize.literal in Review.js

- [sequelize.literal('(SELECT COUNT(*) FROM vote WHERE review.id = vote.review_id)'),
INSTEAD OF 
- [sequelize.literal('(SELECT COUNT(*) FROM vote WHERE review.id = vote.review_id'),

other than that looks good

**Comment by browniecharl** [comment]
Thanks man, I'll take a look at it in the morning

**Comment by browniecharl** [comment]
fixed the typo but it didnt help with displaying the like count on the single review page. still committed to fix the typo and push the rest of the code in case you guys wanted to look at it.

**Review by Arankin7 — APPROVED** [review]

**Review by Arankin7 — APPROVED** [review]

**Review by Arankin7 — APPROVED** [review]

**Comment by Arankin7** [comment]
Won't let me merge it.  
"Merging can be performed automatically once the requested changes are addressed."
I'm guessing Kenny might have to approve it because he requested the changes.

**Comment by browniecharl** [comment]
Yea I think you might be right. as soon as he approves and we can figure out that bug we should be pretty much good to go

**Pull request merged**
